// Generated by gencpp from file control/VelocityReport.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_VELOCITYREPORT_H
#define CONTROL_MESSAGE_VELOCITYREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace control
{
template <class ContainerAllocator>
struct VelocityReport_
{
  typedef VelocityReport_<ContainerAllocator> Type;

  VelocityReport_()
    : header()
    , speed(0.0)  {
    }
  VelocityReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::control::VelocityReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control::VelocityReport_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityReport_

typedef ::control::VelocityReport_<std::allocator<void> > VelocityReport;

typedef boost::shared_ptr< ::control::VelocityReport > VelocityReportPtr;
typedef boost::shared_ptr< ::control::VelocityReport const> VelocityReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control::VelocityReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control::VelocityReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'control': ['/home/auto/Control/src/control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control::VelocityReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::VelocityReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::VelocityReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::VelocityReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::VelocityReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::VelocityReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control::VelocityReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d97c628937d47552ba5fcce4399ed962";
  }

  static const char* value(const ::control::VelocityReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd97c628937d47552ULL;
  static const uint64_t static_value2 = 0xba5fcce4399ed962ULL;
};

template<class ContainerAllocator>
struct DataType< ::control::VelocityReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control/VelocityReport";
  }

  static const char* value(const ::control::VelocityReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control::VelocityReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 speed                     # m/s\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::control::VelocityReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control::VelocityReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control::VelocityReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control::VelocityReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MESSAGE_VELOCITYREPORT_H
