// Generated by gencpp from file can_channel/ModeCmd.msg
// DO NOT EDIT!


#ifndef CAN_CHANNEL_MESSAGE_MODECMD_H
#define CAN_CHANNEL_MESSAGE_MODECMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_channel
{
template <class ContainerAllocator>
struct ModeCmd_
{
  typedef ModeCmd_<ContainerAllocator> Type;

  ModeCmd_()
    : header()
    , mode(0)  {
    }
  ModeCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::can_channel::ModeCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_channel::ModeCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ModeCmd_

typedef ::can_channel::ModeCmd_<std::allocator<void> > ModeCmd;

typedef boost::shared_ptr< ::can_channel::ModeCmd > ModeCmdPtr;
typedef boost::shared_ptr< ::can_channel::ModeCmd const> ModeCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_channel::ModeCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_channel::ModeCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_channel

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'can_channel': ['/home/auto/Control/src/can_channel/msg'], 'can_msgs': ['/opt/ros/kinetic/share/can_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_channel::ModeCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_channel::ModeCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_channel::ModeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_channel::ModeCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_channel::ModeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_channel::ModeCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_channel::ModeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b678d03852da9044784d49ed8fcc636e";
  }

  static const char* value(const ::can_channel::ModeCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb678d03852da9044ULL;
  static const uint64_t static_value2 = 0x784d49ed8fcc636eULL;
};

template<class ContainerAllocator>
struct DataType< ::can_channel::ModeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_channel/ModeCmd";
  }

  static const char* value(const ::can_channel::ModeCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_channel::ModeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 mode\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::can_channel::ModeCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_channel::ModeCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_channel::ModeCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_channel::ModeCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_CHANNEL_MESSAGE_MODECMD_H
