# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control/ControlDebug.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ControlDebug(genpy.Message):
  _md5sum = "56d46489b2fb811d53877106c35e508e"
  _type = "control/ControlDebug"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float64 CurrentSpeed                     # m/s
float64 TargetSpeed                      # m/s
float64 SpeedError                       # m/s
float64 AccelerationCmd                  # m/ss
float64 Curvature                        # rad
float64 LatError                         # m
float64 DirError                         # rad
float64 SteeringAngleCmd                 # rad
float64 CurvatureContribution            # rad
float64 LatContribution                  # rad
float64 DirContribution                  # rad
geometry_msgs/Pose CurrentPose
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','CurrentSpeed','TargetSpeed','SpeedError','AccelerationCmd','Curvature','LatError','DirError','SteeringAngleCmd','CurvatureContribution','LatContribution','DirContribution','CurrentPose']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,CurrentSpeed,TargetSpeed,SpeedError,AccelerationCmd,Curvature,LatError,DirError,SteeringAngleCmd,CurvatureContribution,LatContribution,DirContribution,CurrentPose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControlDebug, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.CurrentSpeed is None:
        self.CurrentSpeed = 0.
      if self.TargetSpeed is None:
        self.TargetSpeed = 0.
      if self.SpeedError is None:
        self.SpeedError = 0.
      if self.AccelerationCmd is None:
        self.AccelerationCmd = 0.
      if self.Curvature is None:
        self.Curvature = 0.
      if self.LatError is None:
        self.LatError = 0.
      if self.DirError is None:
        self.DirError = 0.
      if self.SteeringAngleCmd is None:
        self.SteeringAngleCmd = 0.
      if self.CurvatureContribution is None:
        self.CurvatureContribution = 0.
      if self.LatContribution is None:
        self.LatContribution = 0.
      if self.DirContribution is None:
        self.DirContribution = 0.
      if self.CurrentPose is None:
        self.CurrentPose = geometry_msgs.msg.Pose()
    else:
      self.header = std_msgs.msg.Header()
      self.CurrentSpeed = 0.
      self.TargetSpeed = 0.
      self.SpeedError = 0.
      self.AccelerationCmd = 0.
      self.Curvature = 0.
      self.LatError = 0.
      self.DirError = 0.
      self.SteeringAngleCmd = 0.
      self.CurvatureContribution = 0.
      self.LatContribution = 0.
      self.DirContribution = 0.
      self.CurrentPose = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_18d().pack(_x.CurrentSpeed, _x.TargetSpeed, _x.SpeedError, _x.AccelerationCmd, _x.Curvature, _x.LatError, _x.DirError, _x.SteeringAngleCmd, _x.CurvatureContribution, _x.LatContribution, _x.DirContribution, _x.CurrentPose.position.x, _x.CurrentPose.position.y, _x.CurrentPose.position.z, _x.CurrentPose.orientation.x, _x.CurrentPose.orientation.y, _x.CurrentPose.orientation.z, _x.CurrentPose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.CurrentPose is None:
        self.CurrentPose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 144
      (_x.CurrentSpeed, _x.TargetSpeed, _x.SpeedError, _x.AccelerationCmd, _x.Curvature, _x.LatError, _x.DirError, _x.SteeringAngleCmd, _x.CurvatureContribution, _x.LatContribution, _x.DirContribution, _x.CurrentPose.position.x, _x.CurrentPose.position.y, _x.CurrentPose.position.z, _x.CurrentPose.orientation.x, _x.CurrentPose.orientation.y, _x.CurrentPose.orientation.z, _x.CurrentPose.orientation.w,) = _get_struct_18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_18d().pack(_x.CurrentSpeed, _x.TargetSpeed, _x.SpeedError, _x.AccelerationCmd, _x.Curvature, _x.LatError, _x.DirError, _x.SteeringAngleCmd, _x.CurvatureContribution, _x.LatContribution, _x.DirContribution, _x.CurrentPose.position.x, _x.CurrentPose.position.y, _x.CurrentPose.position.z, _x.CurrentPose.orientation.x, _x.CurrentPose.orientation.y, _x.CurrentPose.orientation.z, _x.CurrentPose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.CurrentPose is None:
        self.CurrentPose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 144
      (_x.CurrentSpeed, _x.TargetSpeed, _x.SpeedError, _x.AccelerationCmd, _x.Curvature, _x.LatError, _x.DirError, _x.SteeringAngleCmd, _x.CurvatureContribution, _x.LatContribution, _x.DirContribution, _x.CurrentPose.position.x, _x.CurrentPose.position.y, _x.CurrentPose.position.z, _x.CurrentPose.orientation.x, _x.CurrentPose.orientation.y, _x.CurrentPose.orientation.z, _x.CurrentPose.orientation.w,) = _get_struct_18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_18d = None
def _get_struct_18d():
    global _struct_18d
    if _struct_18d is None:
        _struct_18d = struct.Struct("<18d")
    return _struct_18d
