(cl:in-package control-msg)
(cl:export '(HEADER-VAL
          HEADER
          CURRENTSPEED-VAL
          CURRENTSPEED
          TARGETSPEED-VAL
          TARGETSPEED
          SPEEDERROR-VAL
          SPEEDERROR
          ACCELERATIONCMD-VAL
          ACCELERATIONCMD
          CURVATURE-VAL
          CURVATURE
          LATERROR-VAL
          LATERROR
          DIRERROR-VAL
          DIRERROR
          STEERINGANGLECMD-VAL
          STEERINGANGLECMD
          CURVATURECONTRIBUTION-VAL
          CURVATURECONTRIBUTION
          LATCONTRIBUTION-VAL
          LATCONTRIBUTION
          DIRCONTRIBUTION-VAL
          DIRCONTRIBUTION
          CURRENTPOSE-VAL
          CURRENTPOSE
))